project:
  type: book
  output-dir: docs

book:
  # title: &book_title "The Little Book of Maths"
  title: &book_title "The Little Chronicles of Mathematics, and the Mind of Machines (TLC3M)"
  subtitle: &book_subtitle "Version 0.2.1"
  author: &book_author "Duc-Tam Nguyen"
  date: &book_date "2025-09-30"
  output-file: book
  chapters:
    - index.qmd
    - books/en-US/tales.qmd
    # - books/en-US/chronicles.md
    # - books/en-US/mini-chronicles-1.md
    # - books/en-US/mini-chronicles-2.md
    - books/en-US/ideas.md
    - books/en-US/chronicles-1.md
    - books/en-US/chronicles-2.md
    - books/en-US/chronicles-3.md
    - books/en-US/chronicles-4.md
    - books/en-US/chronicles-5.md
    - books/en-US/chronicles-6.md
    - books/en-US/chronicles-7.md
    - books/en-US/chronicles-8.md
    - books/en-US/chronicles-9.md
    - books/en-US/chronicles-10.md
    - books/en-US/chronicles-a.md
    - books/en-US/chronicles-b.md
    - books/en-US/chronicles-c.md

website:
  title: *book_title
  page-navigation: true
  navbar:
    search: true
    right:
      - text: *book_subtitle 
      - icon: github
        href: https://github.com/little-book-of/maths
        aria-label: GitHub

format:
  html:
    sidebar: true
    toc: true
    toc-location: left
    toc-depth: 3
    number-sections: false
    theme: [cosmo, brand]
    from: markdown+autolink_bare_uris
  epub:
    title: *book_title
    subtitle: *book_subtitle
    author: *book_author
    date: *book_date
    toc: true 
    toc-depth: 3
    number-sections: false
  pdf:
    title: *book_title
    subtitle: *book_subtitle
    author: *book_author
    date: *book_date
    toc: true 
    toc-depth: 3
    number-sections: false
    colorlinks: true
  latex:
    number-sections: false
